# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-03 18:23
from __future__ import unicode_literals

from django.db import migrations, models
from djangocms_text_ckeditor.fields import HTMLField


class Migration(migrations.Migration):
    initial = True

    operations = [
        migrations.CreateModel(
            name='DummyLink',
            fields=[
                ('label', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('cms.cmsplugin',),
        ),

        migrations.CreateModel(
            name='SimpleText',
            fields=[
                ('text', HTMLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
